# .github/workflows/node-ci.yml
name: Reusable Node CI

on:
  workflow_call:
    inputs:
      run-command:
        required: true
        type: string
      cache-key-prefix:
        required: false
        type: string
        default: node

jobs:
  node-ci-job:
    name: Node Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-

      - name: Install dependencies
        run: npm ci

      - name: Run user-defined command
        run: ${{ inputs.run-command }}
